-- FinTrack initial schema.
--
-- Conventions used throughout:
--   * UUID primary keys, generated by Postgres (gen_random_uuid() is core since PG13).
--   * Money is NUMERIC(14,2) -> BigDecimal in Java. Never floating point.
--   * Amounts are always POSITIVE; the `type` column carries the sign semantics.
--     A signed-amount design makes "sum of expenses" queries subtly wrong the first
--     time someone stores an expense as a positive number.
--   * Enum-like columns are VARCHAR + CHECK, not Postgres ENUM types: adding a value
--     to a Postgres ENUM requires a migration that cannot run inside a transaction.
--   * Fixed-width-looking codes (currency, colour, token hash) are VARCHAR, not CHAR.
--     Postgres CHAR is bpchar and blank-pads to the declared width, so 'DZ' comes back
--     as 'DZ ' and compares unequal to 'DZ'. VARCHAR caps the length without padding.
--   * Timestamps are TIMESTAMPTZ. The one exception is transactions.occurred_on,
--     which is a DATE: a transaction happens on a calendar day, and storing it as an
--     instant invites off-by-one-day bugs the moment a user crosses a timezone.

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(120) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    base_currency VARCHAR(3)   NOT NULL DEFAULT 'DZD',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- Case-insensitive uniqueness. Storing the address as typed but matching folded
-- means "Hamed@x.com" cannot register twice as "hamed@x.com".
CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));


CREATE TABLE refresh_tokens (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- SHA-256 hex of the token. The raw token is returned to the client once and
    -- never stored, so a database leak does not hand out live sessions.
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    user_agent VARCHAR(255),
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);


CREATE TABLE categories (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- NULL user_id marks a global default category, shared by every account.
    user_id    UUID REFERENCES users (id) ON DELETE CASCADE,
    name       VARCHAR(80) NOT NULL,
    type       VARCHAR(10) NOT NULL,
    color      VARCHAR(7),
    icon       VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT categories_type_check CHECK (type IN ('EXPENSE', 'INCOME')),
    CONSTRAINT categories_color_check CHECK (color IS NULL OR color ~ '^#[0-9a-fA-F]{6}$')
);

-- Two partial indexes rather than one constraint: a plain UNIQUE over
-- (user_id, name, type) would not constrain the global rows at all, because in SQL
-- NULL is never equal to NULL.
CREATE UNIQUE INDEX categories_user_name_key
    ON categories (user_id, lower(name), type) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX categories_global_name_key
    ON categories (lower(name), type) WHERE user_id IS NULL;


CREATE TABLE transactions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- Deleting a category keeps its transactions; they simply become uncategorised.
    category_id UUID          REFERENCES categories (id) ON DELETE SET NULL,
    type        VARCHAR(10)   NOT NULL,
    amount      NUMERIC(14, 2) NOT NULL,
    currency    VARCHAR(3)    NOT NULL,
    description VARCHAR(255),
    merchant    VARCHAR(120),
    occurred_on DATE          NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT transactions_type_check CHECK (type IN ('EXPENSE', 'INCOME')),
    CONSTRAINT transactions_amount_check CHECK (amount > 0)
);

-- The dashboard and every list view read one user's rows newest-first, so the
-- index carries the sort order to avoid a sort node on the hot path.
CREATE INDEX idx_transactions_user_date ON transactions (user_id, occurred_on DESC);
CREATE INDEX idx_transactions_category ON transactions (category_id);


CREATE TABLE budgets (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    period_year  INT         NOT NULL,
    period_month INT         NOT NULL,
    currency     VARCHAR(3)  NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT budgets_month_check CHECK (period_month BETWEEN 1 AND 12),
    CONSTRAINT budgets_year_check CHECK (period_year BETWEEN 2000 AND 2100),
    CONSTRAINT budgets_user_period_key UNIQUE (user_id, period_year, period_month)
);


CREATE TABLE budget_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    budget_id       UUID           NOT NULL REFERENCES budgets (id) ON DELETE CASCADE,
    category_id     UUID           NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    limit_amount    NUMERIC(14, 2) NOT NULL,
    -- Fraction of limit_amount at which the user wants to be warned (0.80 = 80%).
    alert_threshold NUMERIC(3, 2)  NOT NULL DEFAULT 0.80,
    CONSTRAINT budget_items_limit_check CHECK (limit_amount > 0),
    CONSTRAINT budget_items_threshold_check CHECK (alert_threshold > 0 AND alert_threshold <= 1),
    CONSTRAINT budget_items_budget_category_key UNIQUE (budget_id, category_id)
);

CREATE INDEX idx_budget_items_budget ON budget_items (budget_id);


-- Keep updated_at honest even for writes that bypass JPA (migrations, psql, imports).
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER transactions_set_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
